// Code generated by goplus from domain.gp. DO NOT EDIT.
//goplus:v v0.24.0

// Package domain contains tbd's closed workflow vocabulary. It is authored in
// Go+ so additions require exhaustive handling by semantic reducers.
package domain

//goplus:enum WorkKind
type WorkKind interface{ isWorkKind() }

//goplus:variant (WorkKind) Feature()
type Feature struct{}

func (Feature) isWorkKind() {}

//goplus:variant (WorkKind) Fix()
type Fix struct{}

func (Fix) isWorkKind() {}

// WorkKindCases selects one handler per WorkKind variant for WorkKindFold.
type WorkKindCases[R any] struct {
	Feature func() R
	Fix     func() R
}

// WorkKindFold reduces WorkKind by one-level case analysis.
func WorkKindFold[R any](w WorkKind, cs WorkKindCases[R]) R {
	switch any(w).(type) {
	case Feature:
		return cs.Feature()
	case Fix:
		return cs.Fix()
	default:
		panic("goplus: impossible enum value in WorkKindFold")
	}
}

// WorkKindEqOverrides carries optional per-variant hooks for WorkKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type WorkKindEqOverrides struct {
	Feature func(x, y Feature) (eq, handled bool)
	Fix     func(x, y Fix) (eq, handled bool)
}

// WorkKindEqualWith reports structural equality of a and b under ov.
func WorkKindEqualWith(a, b WorkKind, ov WorkKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Feature:
		y, ok := any(b).(Feature)
		if !ok {
			return false
		}
		if ov.Feature != nil {
			if eq, handled := ov.Feature(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Fix:
		y, ok := any(b).(Fix)
		if !ok {
			return false
		}
		if ov.Fix != nil {
			if eq, handled := ov.Fix(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// WorkKindEqual reports structural equality of a and b.
func WorkKindEqual(a, b WorkKind) bool {
	return WorkKindEqualWith(a, b, WorkKindEqOverrides{})
}

//goplus:enum GroupKind
type GroupKind interface{ isGroupKind() }

//goplus:variant (GroupKind) Collaboration()
type Collaboration struct{}

func (Collaboration) isGroupKind() {}

//goplus:variant (GroupKind) Stack()
type Stack struct{}

func (Stack) isGroupKind() {}

// GroupKindCases selects one handler per GroupKind variant for GroupKindFold.
type GroupKindCases[R any] struct {
	Collaboration func() R
	Stack         func() R
}

// GroupKindFold reduces GroupKind by one-level case analysis.
func GroupKindFold[R any](g GroupKind, cs GroupKindCases[R]) R {
	switch any(g).(type) {
	case Collaboration:
		return cs.Collaboration()
	case Stack:
		return cs.Stack()
	default:
		panic("goplus: impossible enum value in GroupKindFold")
	}
}

// GroupKindEqOverrides carries optional per-variant hooks for GroupKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type GroupKindEqOverrides struct {
	Collaboration func(x, y Collaboration) (eq, handled bool)
	Stack         func(x, y Stack) (eq, handled bool)
}

// GroupKindEqualWith reports structural equality of a and b under ov.
func GroupKindEqualWith(a, b GroupKind, ov GroupKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Collaboration:
		y, ok := any(b).(Collaboration)
		if !ok {
			return false
		}
		if ov.Collaboration != nil {
			if eq, handled := ov.Collaboration(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Stack:
		y, ok := any(b).(Stack)
		if !ok {
			return false
		}
		if ov.Stack != nil {
			if eq, handled := ov.Stack(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// GroupKindEqual reports structural equality of a and b.
func GroupKindEqual(a, b GroupKind) bool {
	return GroupKindEqualWith(a, b, GroupKindEqOverrides{})
}

//goplus:enum ItemStatus
type ItemStatus interface{ isItemStatus() }

//goplus:variant (ItemStatus) Started()
type Started struct{}

func (Started) isItemStatus() {}

//goplus:variant (ItemStatus) Aggregated(kind GroupKind)
type Aggregated struct {
	Kind GroupKind
}

func (Aggregated) isItemStatus() {}

//goplus:variant (ItemStatus) Finished()
type Finished struct{}

func (Finished) isItemStatus() {}

// ItemStatusCases selects one handler per ItemStatus variant for ItemStatusFold.
type ItemStatusCases[R any] struct {
	Started    func() R
	Aggregated func(kind GroupKind) R
	Finished   func() R
}

// ItemStatusFold reduces ItemStatus by one-level case analysis.
func ItemStatusFold[R any](i ItemStatus, cs ItemStatusCases[R]) R {
	switch m := any(i).(type) {
	case Started:
		return cs.Started()
	case Aggregated:
		return cs.Aggregated(m.Kind)
	case Finished:
		return cs.Finished()
	default:
		panic("goplus: impossible enum value in ItemStatusFold")
	}
}

// ItemStatusEqOverrides carries optional per-variant hooks for ItemStatusEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ItemStatusEqOverrides struct {
	Started    func(x, y Started) (eq, handled bool)
	Aggregated func(x, y Aggregated) (eq, handled bool)
	Finished   func(x, y Finished) (eq, handled bool)
}

// ItemStatusEqualWith reports structural equality of a and b under ov.
func ItemStatusEqualWith(a, b ItemStatus, ov ItemStatusEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Started:
		y, ok := any(b).(Started)
		if !ok {
			return false
		}
		if ov.Started != nil {
			if eq, handled := ov.Started(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Aggregated:
		y, ok := any(b).(Aggregated)
		if !ok {
			return false
		}
		if ov.Aggregated != nil {
			if eq, handled := ov.Aggregated(x, y); handled {
				return eq
			}
		}
		if !GroupKindEqual(x.Kind, y.Kind) {
			return false
		}
		return true
	case Finished:
		y, ok := any(b).(Finished)
		if !ok {
			return false
		}
		if ov.Finished != nil {
			if eq, handled := ov.Finished(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ItemStatusEqual reports structural equality of a and b.
func ItemStatusEqual(a, b ItemStatus) bool {
	return ItemStatusEqualWith(a, b, ItemStatusEqOverrides{})
}

//goplus:enum ReleaseEventKind
type ReleaseEventKind interface{ isReleaseEventKind() }

//goplus:variant (ReleaseEventKind) Candidate()
type Candidate struct{}

func (Candidate) isReleaseEventKind() {}

//goplus:variant (ReleaseEventKind) Released()
type Released struct{}

func (Released) isReleaseEventKind() {}

//goplus:variant (ReleaseEventKind) Invalidated()
type Invalidated struct{}

func (Invalidated) isReleaseEventKind() {}

// ReleaseEventKindCases selects one handler per ReleaseEventKind variant for ReleaseEventKindFold.
type ReleaseEventKindCases[R any] struct {
	Candidate   func() R
	Released    func() R
	Invalidated func() R
}

// ReleaseEventKindFold reduces ReleaseEventKind by one-level case analysis.
func ReleaseEventKindFold[R any](v ReleaseEventKind, cs ReleaseEventKindCases[R]) R {
	switch any(v).(type) {
	case Candidate:
		return cs.Candidate()
	case Released:
		return cs.Released()
	case Invalidated:
		return cs.Invalidated()
	default:
		panic("goplus: impossible enum value in ReleaseEventKindFold")
	}
}

// ReleaseEventKindEqOverrides carries optional per-variant hooks for ReleaseEventKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ReleaseEventKindEqOverrides struct {
	Candidate   func(x, y Candidate) (eq, handled bool)
	Released    func(x, y Released) (eq, handled bool)
	Invalidated func(x, y Invalidated) (eq, handled bool)
}

// ReleaseEventKindEqualWith reports structural equality of a and b under ov.
func ReleaseEventKindEqualWith(a, b ReleaseEventKind, ov ReleaseEventKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Candidate:
		y, ok := any(b).(Candidate)
		if !ok {
			return false
		}
		if ov.Candidate != nil {
			if eq, handled := ov.Candidate(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Released:
		y, ok := any(b).(Released)
		if !ok {
			return false
		}
		if ov.Released != nil {
			if eq, handled := ov.Released(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Invalidated:
		y, ok := any(b).(Invalidated)
		if !ok {
			return false
		}
		if ov.Invalidated != nil {
			if eq, handled := ov.Invalidated(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ReleaseEventKindEqual reports structural equality of a and b.
func ReleaseEventKindEqual(a, b ReleaseEventKind) bool {
	return ReleaseEventKindEqualWith(a, b, ReleaseEventKindEqOverrides{})
}

//goplus:enum RefStrategy
type RefStrategy interface{ isRefStrategy() }

//goplus:variant (RefStrategy) Tag()
type Tag struct{}

func (Tag) isRefStrategy() {}

//goplus:variant (RefStrategy) Branch(prefix string)
type Branch struct {
	Prefix string
}

func (Branch) isRefStrategy() {}

// RefStrategyCases selects one handler per RefStrategy variant for RefStrategyFold.
type RefStrategyCases[R any] struct {
	Tag    func() R
	Branch func(prefix string) R
}

// RefStrategyFold reduces RefStrategy by one-level case analysis.
func RefStrategyFold[R any](v RefStrategy, cs RefStrategyCases[R]) R {
	switch m := any(v).(type) {
	case Tag:
		return cs.Tag()
	case Branch:
		return cs.Branch(m.Prefix)
	default:
		panic("goplus: impossible enum value in RefStrategyFold")
	}
}

// RefStrategyEqOverrides carries optional per-variant hooks for RefStrategyEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type RefStrategyEqOverrides struct {
	Tag    func(x, y Tag) (eq, handled bool)
	Branch func(x, y Branch) (eq, handled bool)
}

// RefStrategyEqualWith reports structural equality of a and b under ov.
func RefStrategyEqualWith(a, b RefStrategy, ov RefStrategyEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Tag:
		y, ok := any(b).(Tag)
		if !ok {
			return false
		}
		if ov.Tag != nil {
			if eq, handled := ov.Tag(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Branch:
		y, ok := any(b).(Branch)
		if !ok {
			return false
		}
		if ov.Branch != nil {
			if eq, handled := ov.Branch(x, y); handled {
				return eq
			}
		}
		if x.Prefix != y.Prefix {
			return false
		}
		return true
	}
	return false
}

// RefStrategyEqual reports structural equality of a and b.
func RefStrategyEqual(a, b RefStrategy) bool {
	return RefStrategyEqualWith(a, b, RefStrategyEqOverrides{})
}

//goplus:enum PushPolicy
type PushPolicy interface{ isPushPolicy() }

//goplus:variant (PushPolicy) ForceWithLease()
type ForceWithLease struct{}

func (ForceWithLease) isPushPolicy() {}

//goplus:variant (PushPolicy) Force()
type Force struct{}

func (Force) isPushPolicy() {}

// PushPolicyCases selects one handler per PushPolicy variant for PushPolicyFold.
type PushPolicyCases[R any] struct {
	ForceWithLease func() R
	Force          func() R
}

// PushPolicyFold reduces PushPolicy by one-level case analysis.
func PushPolicyFold[R any](p PushPolicy, cs PushPolicyCases[R]) R {
	switch any(p).(type) {
	case ForceWithLease:
		return cs.ForceWithLease()
	case Force:
		return cs.Force()
	default:
		panic("goplus: impossible enum value in PushPolicyFold")
	}
}

// PushPolicyEqOverrides carries optional per-variant hooks for PushPolicyEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PushPolicyEqOverrides struct {
	ForceWithLease func(x, y ForceWithLease) (eq, handled bool)
	Force          func(x, y Force) (eq, handled bool)
}

// PushPolicyEqualWith reports structural equality of a and b under ov.
func PushPolicyEqualWith(a, b PushPolicy, ov PushPolicyEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ForceWithLease:
		y, ok := any(b).(ForceWithLease)
		if !ok {
			return false
		}
		if ov.ForceWithLease != nil {
			if eq, handled := ov.ForceWithLease(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Force:
		y, ok := any(b).(Force)
		if !ok {
			return false
		}
		if ov.Force != nil {
			if eq, handled := ov.Force(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// PushPolicyEqual reports structural equality of a and b.
func PushPolicyEqual(a, b PushPolicy) bool {
	return PushPolicyEqualWith(a, b, PushPolicyEqOverrides{})
}

//goplus:enum UATStatus
type UATStatus interface{ isUATStatus() }

//goplus:variant (UATStatus) Pending()
type Pending struct{}

func (Pending) isUATStatus() {}

//goplus:variant (UATStatus) Valid(candidate string, commit string)
type Valid struct {
	Candidate string
	Commit    string
}

func (Valid) isUATStatus() {}

//goplus:variant (UATStatus) Invalid(reason string)
type Invalid struct {
	Reason string
}

func (Invalid) isUATStatus() {}

// UATStatusCases selects one handler per UATStatus variant for UATStatusFold.
type UATStatusCases[R any] struct {
	Pending func() R
	Valid   func(candidate string, commit string) R
	Invalid func(reason string) R
}

// UATStatusFold reduces UATStatus by one-level case analysis.
func UATStatusFold[R any](u UATStatus, cs UATStatusCases[R]) R {
	switch m := any(u).(type) {
	case Pending:
		return cs.Pending()
	case Valid:
		return cs.Valid(m.Candidate, m.Commit)
	case Invalid:
		return cs.Invalid(m.Reason)
	default:
		panic("goplus: impossible enum value in UATStatusFold")
	}
}

// UATStatusEqOverrides carries optional per-variant hooks for UATStatusEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type UATStatusEqOverrides struct {
	Pending func(x, y Pending) (eq, handled bool)
	Valid   func(x, y Valid) (eq, handled bool)
	Invalid func(x, y Invalid) (eq, handled bool)
}

// UATStatusEqualWith reports structural equality of a and b under ov.
func UATStatusEqualWith(a, b UATStatus, ov UATStatusEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Pending:
		y, ok := any(b).(Pending)
		if !ok {
			return false
		}
		if ov.Pending != nil {
			if eq, handled := ov.Pending(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Valid:
		y, ok := any(b).(Valid)
		if !ok {
			return false
		}
		if ov.Valid != nil {
			if eq, handled := ov.Valid(x, y); handled {
				return eq
			}
		}
		if x.Candidate != y.Candidate {
			return false
		}
		if x.Commit != y.Commit {
			return false
		}
		return true
	case Invalid:
		y, ok := any(b).(Invalid)
		if !ok {
			return false
		}
		if ov.Invalid != nil {
			if eq, handled := ov.Invalid(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// UATStatusEqual reports structural equality of a and b.
func UATStatusEqual(a, b UATStatus) bool {
	return UATStatusEqualWith(a, b, UATStatusEqOverrides{})
}

//goplus:enum LeaseState
type LeaseState interface{ isLeaseState() }

//goplus:variant (LeaseState) Unset()
type Unset struct{}

func (Unset) isLeaseState() {}

//goplus:variant (LeaseState) Current(commit string)
type Current struct {
	Commit string
}

func (Current) isLeaseState() {}

//goplus:variant (LeaseState) Stale(previous string, destination string)
type Stale struct {
	Previous    string
	Destination string
}

func (Stale) isLeaseState() {}

//goplus:variant (LeaseState) Foreign(commit string)
type Foreign struct {
	Commit string
}

func (Foreign) isLeaseState() {}

// LeaseStateCases selects one handler per LeaseState variant for LeaseStateFold.
type LeaseStateCases[R any] struct {
	Unset   func() R
	Current func(commit string) R
	Stale   func(previous string, destination string) R
	Foreign func(commit string) R
}

// LeaseStateFold reduces LeaseState by one-level case analysis.
func LeaseStateFold[R any](l LeaseState, cs LeaseStateCases[R]) R {
	switch m := any(l).(type) {
	case Unset:
		return cs.Unset()
	case Current:
		return cs.Current(m.Commit)
	case Stale:
		return cs.Stale(m.Previous, m.Destination)
	case Foreign:
		return cs.Foreign(m.Commit)
	default:
		panic("goplus: impossible enum value in LeaseStateFold")
	}
}

// LeaseStateEqOverrides carries optional per-variant hooks for LeaseStateEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type LeaseStateEqOverrides struct {
	Unset   func(x, y Unset) (eq, handled bool)
	Current func(x, y Current) (eq, handled bool)
	Stale   func(x, y Stale) (eq, handled bool)
	Foreign func(x, y Foreign) (eq, handled bool)
}

// LeaseStateEqualWith reports structural equality of a and b under ov.
func LeaseStateEqualWith(a, b LeaseState, ov LeaseStateEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Unset:
		y, ok := any(b).(Unset)
		if !ok {
			return false
		}
		if ov.Unset != nil {
			if eq, handled := ov.Unset(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Current:
		y, ok := any(b).(Current)
		if !ok {
			return false
		}
		if ov.Current != nil {
			if eq, handled := ov.Current(x, y); handled {
				return eq
			}
		}
		if x.Commit != y.Commit {
			return false
		}
		return true
	case Stale:
		y, ok := any(b).(Stale)
		if !ok {
			return false
		}
		if ov.Stale != nil {
			if eq, handled := ov.Stale(x, y); handled {
				return eq
			}
		}
		if x.Previous != y.Previous {
			return false
		}
		if x.Destination != y.Destination {
			return false
		}
		return true
	case Foreign:
		y, ok := any(b).(Foreign)
		if !ok {
			return false
		}
		if ov.Foreign != nil {
			if eq, handled := ov.Foreign(x, y); handled {
				return eq
			}
		}
		if x.Commit != y.Commit {
			return false
		}
		return true
	}
	return false
}

// LeaseStateEqual reports structural equality of a and b.
func LeaseStateEqual(a, b LeaseState) bool {
	return LeaseStateEqualWith(a, b, LeaseStateEqOverrides{})
}

func WorkKindName(k WorkKind) string {
	var __gp_v0 string
	switch any(k).(type) {
	case Feature:
		__gp_v0 = "feature"
	case Fix:
		__gp_v0 = "fix"
	default:
		panic("goplus: impossible enum value in match")
	}
	return __gp_v0
}

func GroupKindName(k GroupKind) string {
	var __gp_v1 string
	switch any(k).(type) {
	case Collaboration:
		__gp_v1 = "collab"
	case Stack:
		__gp_v1 = "stack"
	default:
		panic("goplus: impossible enum value in match")
	}
	return __gp_v1
}

func ItemStatusName(s ItemStatus) string {
	var __gp_v2 string
	switch __gp_m2 := any(s).(type) {
	case Started:
		__gp_v2 = "started"
	case Aggregated:
		k := __gp_m2.Kind
		__gp_v2 = GroupKindName(k)
	case Finished:
		__gp_v2 = "finished"
	default:
		panic("goplus: impossible enum value in match")
	}
	return __gp_v2
}

func ReleaseEventKindName(k ReleaseEventKind) string {
	var __gp_v3 string
	switch any(k).(type) {
	case Candidate:
		__gp_v3 = "rc"
	case Released:
		__gp_v3 = "release"
	case Invalidated:
		__gp_v3 = "invalidated"
	default:
		panic("goplus: impossible enum value in match")
	}
	return __gp_v3
}
